/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Id = IDL.Text;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const Timestamp = IDL.Int;
export const Achievement = IDL.Record({
  'id' : Id,
  'title' : IDL.Text,
  'userId' : IDL.Principal,
  'earnedAt' : Timestamp,
  'criteria' : IDL.Vec(IDL.Text),
  'points' : IDL.Nat,
});
export const Certification = IDL.Record({
  'id' : Id,
  'userId' : IDL.Principal,
  'issuedAt' : Timestamp,
  'courseId' : Id,
});
export const CourseTier = IDL.Variant({
  'premium' : IDL.Null,
  'free' : IDL.Null,
  'paid' : IDL.Null,
});
export const CreateCourseForm = IDL.Record({
  'title' : IDL.Text,
  'tier' : CourseTier,
  'description' : IDL.Text,
  'modules' : IDL.Vec(IDL.Text),
});
export const Course = IDL.Record({
  'id' : Id,
  'title' : IDL.Text,
  'free' : IDL.Bool,
  'description' : IDL.Text,
  'created_at' : Timestamp,
  'modules' : IDL.Vec(IDL.Text),
});
export const VirtualDesign = IDL.Record({
  'id' : Id,
  'title' : IDL.Text,
  'userId' : IDL.Principal,
  'createdAt' : Timestamp,
  'steps' : IDL.Vec(IDL.Text),
  'materials' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
});
export const DiscussionReply = IDL.Record({
  'content' : IDL.Text,
  'createdAt' : Timestamp,
  'author' : IDL.Principal,
});
export const DiscussionPost = IDL.Record({
  'id' : Id,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'createdAt' : Timestamp,
  'author' : IDL.Principal,
  'replies' : IDL.Vec(DiscussionReply),
});
export const FashionShow = IDL.Record({
  'id' : Id,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'collections' : IDL.Vec(IDL.Text),
  'scheduledAt' : Timestamp,
});
export const UserTier = IDL.Variant({
  'premium' : IDL.Null,
  'free' : IDL.Null,
  'paid' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'userTier' : UserTier,
  'interests' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'learningPath' : IDL.Vec(Id),
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const PriceTier = IDL.Variant({
  'premium' : IDL.Null,
  'free' : IDL.Null,
  'paid' : IDL.Null,
});
export const Resource = IDL.Record({
  'id' : Id,
  'url' : IDL.Text,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'resourceType' : IDL.Variant({
    'video' : IDL.Null,
    'tool' : IDL.Null,
    'article' : IDL.Null,
  }),
});
export const Quiz = IDL.Record({
  'answers' : IDL.Vec(IDL.Text),
  'questions' : IDL.Vec(IDL.Text),
});
export const CourseLevel = IDL.Variant({
  'intermediate' : IDL.Null,
  'beginner' : IDL.Null,
  'advanced' : IDL.Null,
  'professional' : IDL.Null,
});
export const CourseModule = IDL.Record({
  'id' : Id,
  'title' : IDL.Text,
  'supplementalMaterial' : IDL.Vec(Resource),
  'quizPassingScore' : IDL.Opt(IDL.Nat),
  'resources' : IDL.Vec(Resource),
  'quiz' : IDL.Opt(Quiz),
  'description' : IDL.Text,
  'isFree' : IDL.Bool,
  'level' : CourseLevel,
  'priceTier' : IDL.Opt(PriceTier),
  'videoUrl' : IDL.Opt(IDL.Text),
});
export const CourseDescription = IDL.Record({
  'id' : Id,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'isFree' : IDL.Bool,
  'created_at' : Timestamp,
  'priceTier' : IDL.Opt(PriceTier),
  'modules' : IDL.Vec(CourseModule),
});
export const Complete = IDL.Bool;
export const Progress = IDL.Nat;
export const CourseProgress = IDL.Record({
  'userId' : IDL.Principal,
  'completed' : Complete,
  'lastUpdated' : Timestamp,
  'progress' : Progress,
  'courseId' : Id,
});
export const PaymentStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'failed' : IDL.Null,
});
export const CoursePurchase = IDL.Record({
  'paymentStatus' : PaymentStatus,
  'userId' : IDL.Principal,
  'tier' : CourseTier,
  'purchasedAt' : Timestamp,
  'courseId' : Id,
});
export const AIRecommendation = IDL.Record({
  'recommendationId' : Id,
  'reason' : IDL.Text,
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'add_discussion_reply' : IDL.Func([Id, IDL.Text], [], []),
  'add_mentorship' : IDL.Func([IDL.Principal], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'confirmCheckoutSession' : IDL.Func([IDL.Text, Id], [], []),
  'confirmPaypalPayment' : IDL.Func([IDL.Text], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createPaypalPayment' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'create_achievement' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Vec(IDL.Text)],
      [Achievement],
      [],
    ),
  'create_certification' : IDL.Func([IDL.Principal, Id], [Certification], []),
  'create_course' : IDL.Func([CreateCourseForm], [Course], []),
  'create_design' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)), IDL.Vec(IDL.Text)],
      [VirtualDesign],
      [],
    ),
  'create_discussion' : IDL.Func([IDL.Text, IDL.Text], [DiscussionPost], []),
  'create_fashion_show' : IDL.Func(
      [IDL.Text, IDL.Text, Timestamp, IDL.Vec(IDL.Text)],
      [FashionShow],
      [],
    ),
  'delete_course' : IDL.Func([Id], [], []),
  'delete_design' : IDL.Func([Id], [], []),
  'delete_fashion_show' : IDL.Func([Id], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'get_course' : IDL.Func([Id], [IDL.Opt(Course)], ['query']),
  'get_course_descriptions' : IDL.Func(
      [],
      [IDL.Vec(CourseDescription)],
      ['query'],
    ),
  'get_course_modules' : IDL.Func([], [IDL.Vec(CourseModule)], ['query']),
  'get_courses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
  'get_design' : IDL.Func([Id], [IDL.Opt(VirtualDesign)], ['query']),
  'get_discussions' : IDL.Func([], [IDL.Vec(DiscussionPost)], ['query']),
  'get_fashion_show' : IDL.Func([Id], [IDL.Opt(FashionShow)], ['query']),
  'get_fashion_shows' : IDL.Func([], [IDL.Vec(FashionShow)], ['query']),
  'get_my_achievements' : IDL.Func([], [IDL.Vec(Achievement)], ['query']),
  'get_my_certifications' : IDL.Func([], [IDL.Vec(Certification)], ['query']),
  'get_my_course_progress' : IDL.Func(
      [Id],
      [IDL.Opt(CourseProgress)],
      ['query'],
    ),
  'get_my_designs' : IDL.Func([], [IDL.Vec(VirtualDesign)], ['query']),
  'get_purchased_courses' : IDL.Func([], [IDL.Vec(CoursePurchase)], ['query']),
  'get_recommendations' : IDL.Func([], [IDL.Vec(AIRecommendation)], ['query']),
  'get_user_achievements' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Achievement)],
      ['query'],
    ),
  'get_user_certifications' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Certification)],
      ['query'],
    ),
  'get_user_course_progress' : IDL.Func(
      [IDL.Principal, Id],
      [IDL.Opt(CourseProgress)],
      ['query'],
    ),
  'has_purchased_course' : IDL.Func([Id], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'purchase_course' : IDL.Func([Id, CourseTier], [], []),
  'requestApproval' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'update_course' : IDL.Func([Id, CreateCourseForm], [], []),
  'update_course_progress' : IDL.Func([Id, Progress], [], []),
  'update_design' : IDL.Func(
      [Id, IDL.Text, IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)), IDL.Vec(IDL.Text)],
      [],
      [],
    ),
  'update_fashion_show' : IDL.Func(
      [Id, IDL.Text, IDL.Text, Timestamp, IDL.Vec(IDL.Text)],
      [],
      [],
    ),
  'update_purchase_status' : IDL.Func(
      [IDL.Principal, Id, PaymentStatus],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Id = IDL.Text;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const Timestamp = IDL.Int;
  const Achievement = IDL.Record({
    'id' : Id,
    'title' : IDL.Text,
    'userId' : IDL.Principal,
    'earnedAt' : Timestamp,
    'criteria' : IDL.Vec(IDL.Text),
    'points' : IDL.Nat,
  });
  const Certification = IDL.Record({
    'id' : Id,
    'userId' : IDL.Principal,
    'issuedAt' : Timestamp,
    'courseId' : Id,
  });
  const CourseTier = IDL.Variant({
    'premium' : IDL.Null,
    'free' : IDL.Null,
    'paid' : IDL.Null,
  });
  const CreateCourseForm = IDL.Record({
    'title' : IDL.Text,
    'tier' : CourseTier,
    'description' : IDL.Text,
    'modules' : IDL.Vec(IDL.Text),
  });
  const Course = IDL.Record({
    'id' : Id,
    'title' : IDL.Text,
    'free' : IDL.Bool,
    'description' : IDL.Text,
    'created_at' : Timestamp,
    'modules' : IDL.Vec(IDL.Text),
  });
  const VirtualDesign = IDL.Record({
    'id' : Id,
    'title' : IDL.Text,
    'userId' : IDL.Principal,
    'createdAt' : Timestamp,
    'steps' : IDL.Vec(IDL.Text),
    'materials' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
  });
  const DiscussionReply = IDL.Record({
    'content' : IDL.Text,
    'createdAt' : Timestamp,
    'author' : IDL.Principal,
  });
  const DiscussionPost = IDL.Record({
    'id' : Id,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'createdAt' : Timestamp,
    'author' : IDL.Principal,
    'replies' : IDL.Vec(DiscussionReply),
  });
  const FashionShow = IDL.Record({
    'id' : Id,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'collections' : IDL.Vec(IDL.Text),
    'scheduledAt' : Timestamp,
  });
  const UserTier = IDL.Variant({
    'premium' : IDL.Null,
    'free' : IDL.Null,
    'paid' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'userTier' : UserTier,
    'interests' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'learningPath' : IDL.Vec(Id),
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const PriceTier = IDL.Variant({
    'premium' : IDL.Null,
    'free' : IDL.Null,
    'paid' : IDL.Null,
  });
  const Resource = IDL.Record({
    'id' : Id,
    'url' : IDL.Text,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'resourceType' : IDL.Variant({
      'video' : IDL.Null,
      'tool' : IDL.Null,
      'article' : IDL.Null,
    }),
  });
  const Quiz = IDL.Record({
    'answers' : IDL.Vec(IDL.Text),
    'questions' : IDL.Vec(IDL.Text),
  });
  const CourseLevel = IDL.Variant({
    'intermediate' : IDL.Null,
    'beginner' : IDL.Null,
    'advanced' : IDL.Null,
    'professional' : IDL.Null,
  });
  const CourseModule = IDL.Record({
    'id' : Id,
    'title' : IDL.Text,
    'supplementalMaterial' : IDL.Vec(Resource),
    'quizPassingScore' : IDL.Opt(IDL.Nat),
    'resources' : IDL.Vec(Resource),
    'quiz' : IDL.Opt(Quiz),
    'description' : IDL.Text,
    'isFree' : IDL.Bool,
    'level' : CourseLevel,
    'priceTier' : IDL.Opt(PriceTier),
    'videoUrl' : IDL.Opt(IDL.Text),
  });
  const CourseDescription = IDL.Record({
    'id' : Id,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'isFree' : IDL.Bool,
    'created_at' : Timestamp,
    'priceTier' : IDL.Opt(PriceTier),
    'modules' : IDL.Vec(CourseModule),
  });
  const Complete = IDL.Bool;
  const Progress = IDL.Nat;
  const CourseProgress = IDL.Record({
    'userId' : IDL.Principal,
    'completed' : Complete,
    'lastUpdated' : Timestamp,
    'progress' : Progress,
    'courseId' : Id,
  });
  const PaymentStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'failed' : IDL.Null,
  });
  const CoursePurchase = IDL.Record({
    'paymentStatus' : PaymentStatus,
    'userId' : IDL.Principal,
    'tier' : CourseTier,
    'purchasedAt' : Timestamp,
    'courseId' : Id,
  });
  const AIRecommendation = IDL.Record({
    'recommendationId' : Id,
    'reason' : IDL.Text,
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'add_discussion_reply' : IDL.Func([Id, IDL.Text], [], []),
    'add_mentorship' : IDL.Func([IDL.Principal], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'confirmCheckoutSession' : IDL.Func([IDL.Text, Id], [], []),
    'confirmPaypalPayment' : IDL.Func([IDL.Text], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createPaypalPayment' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'create_achievement' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Vec(IDL.Text)],
        [Achievement],
        [],
      ),
    'create_certification' : IDL.Func([IDL.Principal, Id], [Certification], []),
    'create_course' : IDL.Func([CreateCourseForm], [Course], []),
    'create_design' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)), IDL.Vec(IDL.Text)],
        [VirtualDesign],
        [],
      ),
    'create_discussion' : IDL.Func([IDL.Text, IDL.Text], [DiscussionPost], []),
    'create_fashion_show' : IDL.Func(
        [IDL.Text, IDL.Text, Timestamp, IDL.Vec(IDL.Text)],
        [FashionShow],
        [],
      ),
    'delete_course' : IDL.Func([Id], [], []),
    'delete_design' : IDL.Func([Id], [], []),
    'delete_fashion_show' : IDL.Func([Id], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'get_course' : IDL.Func([Id], [IDL.Opt(Course)], ['query']),
    'get_course_descriptions' : IDL.Func(
        [],
        [IDL.Vec(CourseDescription)],
        ['query'],
      ),
    'get_course_modules' : IDL.Func([], [IDL.Vec(CourseModule)], ['query']),
    'get_courses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
    'get_design' : IDL.Func([Id], [IDL.Opt(VirtualDesign)], ['query']),
    'get_discussions' : IDL.Func([], [IDL.Vec(DiscussionPost)], ['query']),
    'get_fashion_show' : IDL.Func([Id], [IDL.Opt(FashionShow)], ['query']),
    'get_fashion_shows' : IDL.Func([], [IDL.Vec(FashionShow)], ['query']),
    'get_my_achievements' : IDL.Func([], [IDL.Vec(Achievement)], ['query']),
    'get_my_certifications' : IDL.Func([], [IDL.Vec(Certification)], ['query']),
    'get_my_course_progress' : IDL.Func(
        [Id],
        [IDL.Opt(CourseProgress)],
        ['query'],
      ),
    'get_my_designs' : IDL.Func([], [IDL.Vec(VirtualDesign)], ['query']),
    'get_purchased_courses' : IDL.Func(
        [],
        [IDL.Vec(CoursePurchase)],
        ['query'],
      ),
    'get_recommendations' : IDL.Func(
        [],
        [IDL.Vec(AIRecommendation)],
        ['query'],
      ),
    'get_user_achievements' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Achievement)],
        ['query'],
      ),
    'get_user_certifications' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Certification)],
        ['query'],
      ),
    'get_user_course_progress' : IDL.Func(
        [IDL.Principal, Id],
        [IDL.Opt(CourseProgress)],
        ['query'],
      ),
    'has_purchased_course' : IDL.Func([Id], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'purchase_course' : IDL.Func([Id, CourseTier], [], []),
    'requestApproval' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'update_course' : IDL.Func([Id, CreateCourseForm], [], []),
    'update_course_progress' : IDL.Func([Id, Progress], [], []),
    'update_design' : IDL.Func(
        [
          Id,
          IDL.Text,
          IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
          IDL.Vec(IDL.Text),
        ],
        [],
        [],
      ),
    'update_fashion_show' : IDL.Func(
        [Id, IDL.Text, IDL.Text, Timestamp, IDL.Vec(IDL.Text)],
        [],
        [],
      ),
    'update_purchase_status' : IDL.Func(
        [IDL.Principal, Id, PaymentStatus],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };