/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AIRecommendation { 'recommendationId' : Id, 'reason' : string }
export interface Achievement {
  'id' : Id,
  'title' : string,
  'userId' : Principal,
  'earnedAt' : Timestamp,
  'criteria' : Array<string>,
  'points' : bigint,
}
export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface Certification {
  'id' : Id,
  'userId' : Principal,
  'issuedAt' : Timestamp,
  'courseId' : Id,
}
export type Complete = boolean;
export interface Course {
  'id' : Id,
  'title' : string,
  'free' : boolean,
  'description' : string,
  'created_at' : Timestamp,
  'modules' : Array<string>,
}
export interface CourseDescription {
  'id' : Id,
  'title' : string,
  'description' : string,
  'isFree' : boolean,
  'created_at' : Timestamp,
  'priceTier' : [] | [PriceTier],
  'modules' : Array<CourseModule>,
}
export type CourseLevel = { 'intermediate' : null } |
  { 'beginner' : null } |
  { 'advanced' : null } |
  { 'professional' : null };
export interface CourseModule {
  'id' : Id,
  'title' : string,
  'supplementalMaterial' : Array<Resource>,
  'quizPassingScore' : [] | [bigint],
  'resources' : Array<Resource>,
  'quiz' : [] | [Quiz],
  'description' : string,
  'isFree' : boolean,
  'level' : CourseLevel,
  'priceTier' : [] | [PriceTier],
  'videoUrl' : [] | [string],
}
export interface CourseProgress {
  'userId' : Principal,
  'completed' : Complete,
  'lastUpdated' : Timestamp,
  'progress' : Progress,
  'courseId' : Id,
}
export interface CoursePurchase {
  'paymentStatus' : PaymentStatus,
  'userId' : Principal,
  'tier' : CourseTier,
  'purchasedAt' : Timestamp,
  'courseId' : Id,
}
export type CourseTier = { 'premium' : null } |
  { 'free' : null } |
  { 'paid' : null };
export interface CreateCourseForm {
  'title' : string,
  'tier' : CourseTier,
  'description' : string,
  'modules' : Array<string>,
}
export interface DiscussionPost {
  'id' : Id,
  'title' : string,
  'content' : string,
  'createdAt' : Timestamp,
  'author' : Principal,
  'replies' : Array<DiscussionReply>,
}
export interface DiscussionReply {
  'content' : string,
  'createdAt' : Timestamp,
  'author' : Principal,
}
export interface FashionShow {
  'id' : Id,
  'title' : string,
  'description' : string,
  'collections' : Array<string>,
  'scheduledAt' : Timestamp,
}
export type Id = string;
export type PaymentStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'failed' : null };
export type PriceTier = { 'premium' : null } |
  { 'free' : null } |
  { 'paid' : null };
export type Progress = bigint;
export interface Quiz { 'answers' : Array<string>, 'questions' : Array<string> }
export interface Resource {
  'id' : Id,
  'url' : string,
  'title' : string,
  'description' : string,
  'resourceType' : { 'video' : null } |
    { 'tool' : null } |
    { 'article' : null },
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type Timestamp = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export interface UserProfile {
  'userTier' : UserTier,
  'interests' : Array<string>,
  'name' : string,
  'learningPath' : Array<Id>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type UserTier = { 'premium' : null } |
  { 'free' : null } |
  { 'paid' : null };
export interface VirtualDesign {
  'id' : Id,
  'title' : string,
  'userId' : Principal,
  'createdAt' : Timestamp,
  'steps' : Array<string>,
  'materials' : Array<[string, bigint]>,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'add_discussion_reply' : ActorMethod<[Id, string], undefined>,
  'add_mentorship' : ActorMethod<[Principal], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'confirmCheckoutSession' : ActorMethod<[string, Id], undefined>,
  'confirmPaypalPayment' : ActorMethod<[string], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createPaypalPayment' : ActorMethod<[string, string], undefined>,
  'create_achievement' : ActorMethod<
    [string, bigint, Array<string>],
    Achievement
  >,
  'create_certification' : ActorMethod<[Principal, Id], Certification>,
  'create_course' : ActorMethod<[CreateCourseForm], Course>,
  'create_design' : ActorMethod<
    [string, Array<[string, bigint]>, Array<string>],
    VirtualDesign
  >,
  'create_discussion' : ActorMethod<[string, string], DiscussionPost>,
  'create_fashion_show' : ActorMethod<
    [string, string, Timestamp, Array<string>],
    FashionShow
  >,
  'delete_course' : ActorMethod<[Id], undefined>,
  'delete_design' : ActorMethod<[Id], undefined>,
  'delete_fashion_show' : ActorMethod<[Id], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'get_course' : ActorMethod<[Id], [] | [Course]>,
  'get_course_descriptions' : ActorMethod<[], Array<CourseDescription>>,
  'get_course_modules' : ActorMethod<[], Array<CourseModule>>,
  'get_courses' : ActorMethod<[], Array<Course>>,
  'get_design' : ActorMethod<[Id], [] | [VirtualDesign]>,
  'get_discussions' : ActorMethod<[], Array<DiscussionPost>>,
  'get_fashion_show' : ActorMethod<[Id], [] | [FashionShow]>,
  'get_fashion_shows' : ActorMethod<[], Array<FashionShow>>,
  'get_my_achievements' : ActorMethod<[], Array<Achievement>>,
  'get_my_certifications' : ActorMethod<[], Array<Certification>>,
  'get_my_course_progress' : ActorMethod<[Id], [] | [CourseProgress]>,
  'get_my_designs' : ActorMethod<[], Array<VirtualDesign>>,
  'get_purchased_courses' : ActorMethod<[], Array<CoursePurchase>>,
  'get_recommendations' : ActorMethod<[], Array<AIRecommendation>>,
  'get_user_achievements' : ActorMethod<[Principal], Array<Achievement>>,
  'get_user_certifications' : ActorMethod<[Principal], Array<Certification>>,
  'get_user_course_progress' : ActorMethod<
    [Principal, Id],
    [] | [CourseProgress]
  >,
  'has_purchased_course' : ActorMethod<[Id], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'purchase_course' : ActorMethod<[Id, CourseTier], undefined>,
  'requestApproval' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'update_course' : ActorMethod<[Id, CreateCourseForm], undefined>,
  'update_course_progress' : ActorMethod<[Id, Progress], undefined>,
  'update_design' : ActorMethod<
    [Id, string, Array<[string, bigint]>, Array<string>],
    undefined
  >,
  'update_fashion_show' : ActorMethod<
    [Id, string, string, Timestamp, Array<string>],
    undefined
  >,
  'update_purchase_status' : ActorMethod<
    [Principal, Id, PaymentStatus],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];