/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface FashionShow {
    id: Id;
    title: string;
    description: string;
    collections: Array<string>;
    scheduledAt: Timestamp;
}
export interface DiscussionReply {
    content: string;
    createdAt: Timestamp;
    author: Principal;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface CreateCourseForm {
    title: string;
    tier: CourseTier;
    description: string;
    modules: Array<string>;
}
export interface Quiz {
    answers: Array<string>;
    questions: Array<string>;
}
export interface CourseDescription {
    id: Id;
    title: string;
    description: string;
    isFree: boolean;
    created_at: Timestamp;
    priceTier?: PriceTier;
    modules: Array<CourseModule>;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface DiscussionPost {
    id: Id;
    title: string;
    content: string;
    createdAt: Timestamp;
    author: Principal;
    replies: Array<DiscussionReply>;
}
export interface Course {
    id: Id;
    title: string;
    free: boolean;
    description: string;
    created_at: Timestamp;
    modules: Array<string>;
}
export interface CourseModule {
    id: Id;
    title: string;
    supplementalMaterial: Array<Resource>;
    quizPassingScore?: bigint;
    resources: Array<Resource>;
    quiz?: Quiz;
    description: string;
    isFree: boolean;
    level: CourseLevel;
    priceTier?: PriceTier;
    videoUrl?: string;
}
export interface Achievement {
    id: Id;
    title: string;
    userId: Principal;
    earnedAt: Timestamp;
    criteria: Array<string>;
    points: bigint;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export type StripeSessionStatus = {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
};
export interface StripeConfiguration {
    allowedCountries: Array<string>;
    secretKey: string;
}
export interface CoursePurchase {
    paymentStatus: PaymentStatus;
    userId: Principal;
    tier: CourseTier;
    purchasedAt: Timestamp;
    courseId: Id;
}
export interface VirtualDesign {
    id: Id;
    title: string;
    userId: Principal;
    createdAt: Timestamp;
    steps: Array<string>;
    materials: Array<[string, bigint]>;
}
export type Complete = boolean;
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface UserApprovalInfo {
    status: ApprovalStatus;
    principal: Principal;
}
export interface Certification {
    id: Id;
    userId: Principal;
    issuedAt: Timestamp;
    courseId: Id;
}
export interface ShoppingItem {
    productName: string;
    currency: string;
    quantity: bigint;
    priceInCents: bigint;
    productDescription: string;
}
export interface AIRecommendation {
    recommendationId: Id;
    reason: string;
}
export type Progress = bigint;
export interface Resource {
    id: Id;
    url: string;
    title: string;
    description: string;
    resourceType: Variant_video_tool_article;
}
export type Id = string;
export interface CourseProgress {
    userId: Principal;
    completed: Complete;
    lastUpdated: Timestamp;
    progress: Progress;
    courseId: Id;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface UserProfile {
    userTier: UserTier;
    interests: Array<string>;
    name: string;
    learningPath: Array<Id>;
}
export enum ApprovalStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum CourseLevel {
    intermediate = "intermediate",
    beginner = "beginner",
    advanced = "advanced",
    professional = "professional"
}
export enum PaymentStatus {
    pending = "pending",
    completed = "completed",
    failed = "failed"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum UserTier {
    premium = "premium",
    free = "free",
    paid = "paid"
}
export enum Variant_video_tool_article {
    video = "video",
    tool = "tool",
    article = "article"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    add_discussion_reply(postId: Id, content: string): Promise<void>;
    add_mentorship(mentee: Principal): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    confirmCheckoutSession(sessionId: string, courseId: Id): Promise<void>;
    confirmPaypalPayment(sessionId: string): Promise<void>;
    createCheckoutSession(items: Array<ShoppingItem>, successUrl: string, cancelUrl: string): Promise<string>;
    createPaypalPayment(courseId: string, sessionId: string): Promise<void>;
    create_achievement(title: string, points: bigint, criteria: Array<string>): Promise<Achievement>;
    create_certification(userId: Principal, courseId: Id): Promise<Certification>;
    create_course(form: CreateCourseForm): Promise<Course>;
    create_design(title: string, materials: Array<[string, bigint]>, steps: Array<string>): Promise<VirtualDesign>;
    create_discussion(title: string, content: string): Promise<DiscussionPost>;
    create_fashion_show(title: string, description: string, scheduledAt: Timestamp, collections: Array<string>): Promise<FashionShow>;
    delete_course(courseId: Id): Promise<void>;
    delete_design(designId: Id): Promise<void>;
    delete_fashion_show(showId: Id): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getStripeSessionStatus(sessionId: string): Promise<StripeSessionStatus>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    get_course(courseId: Id): Promise<Course | null>;
    get_course_descriptions(): Promise<Array<CourseDescription>>;
    get_course_modules(): Promise<Array<CourseModule>>;
    get_courses(): Promise<Array<Course>>;
    get_design(designId: Id): Promise<VirtualDesign | null>;
    get_discussions(): Promise<Array<DiscussionPost>>;
    get_fashion_show(showId: Id): Promise<FashionShow | null>;
    get_fashion_shows(): Promise<Array<FashionShow>>;
    get_my_achievements(): Promise<Array<Achievement>>;
    get_my_certifications(): Promise<Array<Certification>>;
    get_my_course_progress(courseId: Id): Promise<CourseProgress | null>;
    get_my_designs(): Promise<Array<VirtualDesign>>;
    get_purchased_courses(): Promise<Array<CoursePurchase>>;
    get_recommendations(): Promise<Array<AIRecommendation>>;
    get_user_achievements(user: Principal): Promise<Array<Achievement>>;
    get_user_certifications(user: Principal): Promise<Array<Certification>>;
    get_user_course_progress(user: Principal, courseId: Id): Promise<CourseProgress | null>;
    has_purchased_course(courseId: Id): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    isCallerApproved(): Promise<boolean>;
    isStripeConfigured(): Promise<boolean>;
    listApprovals(): Promise<Array<UserApprovalInfo>>;
    purchase_course(courseId: Id, tier: CourseTier): Promise<void>;
    requestApproval(): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setApproval(user: Principal, status: ApprovalStatus): Promise<void>;
    setStripeConfiguration(config: StripeConfiguration): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    update_course(courseId: Id, form: CreateCourseForm): Promise<void>;
    update_course_progress(courseId: Id, progress: Progress): Promise<void>;
    update_design(designId: Id, title: string, materials: Array<[string, bigint]>, steps: Array<string>): Promise<void>;
    update_fashion_show(showId: Id, title: string, description: string, scheduledAt: Timestamp, collections: Array<string>): Promise<void>;
    update_purchase_status(userId: Principal, courseId: Id, status: PaymentStatus): Promise<void>;
}
import type { ApprovalStatus as _ApprovalStatus, Course as _Course, CourseDescription as _CourseDescription, CourseLevel as _CourseLevel, CourseModule as _CourseModule, CourseProgress as _CourseProgress, CoursePurchase as _CoursePurchase, CourseTier as _CourseTier, CreateCourseForm as _CreateCourseForm, FashionShow as _FashionShow, Id as _Id, PaymentStatus as _PaymentStatus, PriceTier as _PriceTier, Quiz as _Quiz, Resource as _Resource, StripeSessionStatus as _StripeSessionStatus, Timestamp as _Timestamp, UserApprovalInfo as _UserApprovalInfo, UserProfile as _UserProfile, UserRole as _UserRole, UserTier as _UserTier, VirtualDesign as _VirtualDesign, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async add_discussion_reply(arg0: Id, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.add_discussion_reply(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.add_discussion_reply(arg0, arg1);
            return result;
        }
    }
    async add_mentorship(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.add_mentorship(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.add_mentorship(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async confirmCheckoutSession(arg0: string, arg1: Id): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.confirmCheckoutSession(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.confirmCheckoutSession(arg0, arg1);
            return result;
        }
    }
    async confirmPaypalPayment(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.confirmPaypalPayment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.confirmPaypalPayment(arg0);
            return result;
        }
    }
    async createCheckoutSession(arg0: Array<ShoppingItem>, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async createPaypalPayment(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createPaypalPayment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPaypalPayment(arg0, arg1);
            return result;
        }
    }
    async create_achievement(arg0: string, arg1: bigint, arg2: Array<string>): Promise<Achievement> {
        if (this.processError) {
            try {
                const result = await this.actor.create_achievement(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.create_achievement(arg0, arg1, arg2);
            return result;
        }
    }
    async create_certification(arg0: Principal, arg1: Id): Promise<Certification> {
        if (this.processError) {
            try {
                const result = await this.actor.create_certification(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.create_certification(arg0, arg1);
            return result;
        }
    }
    async create_course(arg0: CreateCourseForm): Promise<Course> {
        if (this.processError) {
            try {
                const result = await this.actor.create_course(to_candid_CreateCourseForm_n10(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.create_course(to_candid_CreateCourseForm_n10(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async create_design(arg0: string, arg1: Array<[string, bigint]>, arg2: Array<string>): Promise<VirtualDesign> {
        if (this.processError) {
            try {
                const result = await this.actor.create_design(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.create_design(arg0, arg1, arg2);
            return result;
        }
    }
    async create_discussion(arg0: string, arg1: string): Promise<DiscussionPost> {
        if (this.processError) {
            try {
                const result = await this.actor.create_discussion(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.create_discussion(arg0, arg1);
            return result;
        }
    }
    async create_fashion_show(arg0: string, arg1: string, arg2: Timestamp, arg3: Array<string>): Promise<FashionShow> {
        if (this.processError) {
            try {
                const result = await this.actor.create_fashion_show(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.create_fashion_show(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async delete_course(arg0: Id): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.delete_course(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.delete_course(arg0);
            return result;
        }
    }
    async delete_design(arg0: Id): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.delete_design(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.delete_design(arg0);
            return result;
        }
    }
    async delete_fashion_show(arg0: Id): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.delete_fashion_show(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.delete_fashion_show(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<StripeSessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return from_candid_StripeSessionStatus_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return from_candid_StripeSessionStatus_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async get_course(arg0: Id): Promise<Course | null> {
        if (this.processError) {
            try {
                const result = await this.actor.get_course(arg0);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.get_course(arg0);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async get_course_descriptions(): Promise<Array<CourseDescription>> {
        if (this.processError) {
            try {
                const result = await this.actor.get_course_descriptions();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.get_course_descriptions();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async get_course_modules(): Promise<Array<CourseModule>> {
        if (this.processError) {
            try {
                const result = await this.actor.get_course_modules();
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.get_course_modules();
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async get_courses(): Promise<Array<Course>> {
        if (this.processError) {
            try {
                const result = await this.actor.get_courses();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.get_courses();
            return result;
        }
    }
    async get_design(arg0: Id): Promise<VirtualDesign | null> {
        if (this.processError) {
            try {
                const result = await this.actor.get_design(arg0);
                return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.get_design(arg0);
            return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async get_discussions(): Promise<Array<DiscussionPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.get_discussions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.get_discussions();
            return result;
        }
    }
    async get_fashion_show(arg0: Id): Promise<FashionShow | null> {
        if (this.processError) {
            try {
                const result = await this.actor.get_fashion_show(arg0);
                return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.get_fashion_show(arg0);
            return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async get_fashion_shows(): Promise<Array<FashionShow>> {
        if (this.processError) {
            try {
                const result = await this.actor.get_fashion_shows();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.get_fashion_shows();
            return result;
        }
    }
    async get_my_achievements(): Promise<Array<Achievement>> {
        if (this.processError) {
            try {
                const result = await this.actor.get_my_achievements();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.get_my_achievements();
            return result;
        }
    }
    async get_my_certifications(): Promise<Array<Certification>> {
        if (this.processError) {
            try {
                const result = await this.actor.get_my_certifications();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.get_my_certifications();
            return result;
        }
    }
    async get_my_course_progress(arg0: Id): Promise<CourseProgress | null> {
        if (this.processError) {
            try {
                const result = await this.actor.get_my_course_progress(arg0);
                return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.get_my_course_progress(arg0);
            return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async get_my_designs(): Promise<Array<VirtualDesign>> {
        if (this.processError) {
            try {
                const result = await this.actor.get_my_designs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.get_my_designs();
            return result;
        }
    }
    async get_purchased_courses(): Promise<Array<CoursePurchase>> {
        if (this.processError) {
            try {
                const result = await this.actor.get_purchased_courses();
                return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.get_purchased_courses();
            return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async get_recommendations(): Promise<Array<AIRecommendation>> {
        if (this.processError) {
            try {
                const result = await this.actor.get_recommendations();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.get_recommendations();
            return result;
        }
    }
    async get_user_achievements(arg0: Principal): Promise<Array<Achievement>> {
        if (this.processError) {
            try {
                const result = await this.actor.get_user_achievements(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.get_user_achievements(arg0);
            return result;
        }
    }
    async get_user_certifications(arg0: Principal): Promise<Array<Certification>> {
        if (this.processError) {
            try {
                const result = await this.actor.get_user_certifications(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.get_user_certifications(arg0);
            return result;
        }
    }
    async get_user_course_progress(arg0: Principal, arg1: Id): Promise<CourseProgress | null> {
        if (this.processError) {
            try {
                const result = await this.actor.get_user_course_progress(arg0, arg1);
                return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.get_user_course_progress(arg0, arg1);
            return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async has_purchased_course(arg0: Id): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.has_purchased_course(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.has_purchased_course(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isCallerApproved(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerApproved();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerApproved();
            return result;
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async listApprovals(): Promise<Array<UserApprovalInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.listApprovals();
                return from_candid_vec_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listApprovals();
            return from_candid_vec_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async purchase_course(arg0: Id, arg1: CourseTier): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.purchase_course(arg0, to_candid_CourseTier_n12(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.purchase_course(arg0, to_candid_CourseTier_n12(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async requestApproval(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.requestApproval();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestApproval();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n55(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n55(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setApproval(arg0: Principal, arg1: ApprovalStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n58(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n58(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async setStripeConfiguration(arg0: StripeConfiguration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async update_course(arg0: Id, arg1: CreateCourseForm): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.update_course(arg0, to_candid_CreateCourseForm_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.update_course(arg0, to_candid_CreateCourseForm_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async update_course_progress(arg0: Id, arg1: Progress): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.update_course_progress(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.update_course_progress(arg0, arg1);
            return result;
        }
    }
    async update_design(arg0: Id, arg1: string, arg2: Array<[string, bigint]>, arg3: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.update_design(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.update_design(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async update_fashion_show(arg0: Id, arg1: string, arg2: string, arg3: Timestamp, arg4: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.update_fashion_show(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.update_fashion_show(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async update_purchase_status(arg0: Principal, arg1: Id, arg2: PaymentStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.update_purchase_status(arg0, arg1, to_candid_PaymentStatus_n60(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.update_purchase_status(arg0, arg1, to_candid_PaymentStatus_n60(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
}
function from_candid_ApprovalStatus_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApprovalStatus): ApprovalStatus {
    return from_candid_variant_n54(_uploadFile, _downloadFile, value);
}
function from_candid_CourseDescription_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CourseDescription): CourseDescription {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_CourseLevel_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CourseLevel): CourseLevel {
    return from_candid_variant_n40(_uploadFile, _downloadFile, value);
}
function from_candid_CourseModule_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CourseModule): CourseModule {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_CoursePurchase_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CoursePurchase): CoursePurchase {
    return from_candid_record_n46(_uploadFile, _downloadFile, value);
}
function from_candid_CourseTier_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CourseTier): CourseTier {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentStatus_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentStatus): PaymentStatus {
    return from_candid_variant_n48(_uploadFile, _downloadFile, value);
}
function from_candid_PriceTier_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PriceTier): PriceTier {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_Resource_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Resource): Resource {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_StripeSessionStatus_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeSessionStatus): StripeSessionStatus {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_UserApprovalInfo_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserApprovalInfo): UserApprovalInfo {
    return from_candid_record_n52(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_UserTier_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserTier): UserTier {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n15(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Course]): Course | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PriceTier]): PriceTier | null {
    return value.length === 0 ? null : from_candid_PriceTier_n30(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Quiz]): Quiz | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_VirtualDesign]): VirtualDesign | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FashionShow]): FashionShow | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CourseProgress]): CourseProgress | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userTier: _UserTier;
    interests: Array<string>;
    name: string;
    learningPath: Array<_Id>;
}): {
    userTier: UserTier;
    interests: Array<string>;
    name: string;
    learningPath: Array<Id>;
} {
    return {
        userTier: from_candid_UserTier_n17(_uploadFile, _downloadFile, value.userTier),
        interests: value.interests,
        name: value.name,
        learningPath: value.learningPath
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
    response: string;
}): {
    userPrincipal?: string;
    response: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.userPrincipal)),
        response: value.response
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _Id;
    title: string;
    description: string;
    isFree: boolean;
    created_at: _Timestamp;
    priceTier: [] | [_PriceTier];
    modules: Array<_CourseModule>;
}): {
    id: Id;
    title: string;
    description: string;
    isFree: boolean;
    created_at: Timestamp;
    priceTier?: PriceTier;
    modules: Array<CourseModule>;
} {
    return {
        id: value.id,
        title: value.title,
        description: value.description,
        isFree: value.isFree,
        created_at: value.created_at,
        priceTier: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.priceTier)),
        modules: from_candid_vec_n31(_uploadFile, _downloadFile, value.modules)
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _Id;
    title: string;
    supplementalMaterial: Array<_Resource>;
    quizPassingScore: [] | [bigint];
    resources: Array<_Resource>;
    quiz: [] | [_Quiz];
    description: string;
    isFree: boolean;
    level: _CourseLevel;
    priceTier: [] | [_PriceTier];
    videoUrl: [] | [string];
}): {
    id: Id;
    title: string;
    supplementalMaterial: Array<Resource>;
    quizPassingScore?: bigint;
    resources: Array<Resource>;
    quiz?: Quiz;
    description: string;
    isFree: boolean;
    level: CourseLevel;
    priceTier?: PriceTier;
    videoUrl?: string;
} {
    return {
        id: value.id,
        title: value.title,
        supplementalMaterial: from_candid_vec_n34(_uploadFile, _downloadFile, value.supplementalMaterial),
        quizPassingScore: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.quizPassingScore)),
        resources: from_candid_vec_n34(_uploadFile, _downloadFile, value.resources),
        quiz: record_opt_to_undefined(from_candid_opt_n38(_uploadFile, _downloadFile, value.quiz)),
        description: value.description,
        isFree: value.isFree,
        level: from_candid_CourseLevel_n39(_uploadFile, _downloadFile, value.level),
        priceTier: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.priceTier)),
        videoUrl: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.videoUrl))
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _Id;
    url: string;
    title: string;
    description: string;
    resourceType: {
        video: null;
    } | {
        tool: null;
    } | {
        article: null;
    };
}): {
    id: Id;
    url: string;
    title: string;
    description: string;
    resourceType: Variant_video_tool_article;
} {
    return {
        id: value.id,
        url: value.url,
        title: value.title,
        description: value.description,
        resourceType: from_candid_variant_n37(_uploadFile, _downloadFile, value.resourceType)
    };
}
function from_candid_record_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    paymentStatus: _PaymentStatus;
    userId: Principal;
    tier: _CourseTier;
    purchasedAt: _Timestamp;
    courseId: _Id;
}): {
    paymentStatus: PaymentStatus;
    userId: Principal;
    tier: CourseTier;
    purchasedAt: Timestamp;
    courseId: Id;
} {
    return {
        paymentStatus: from_candid_PaymentStatus_n47(_uploadFile, _downloadFile, value.paymentStatus),
        userId: value.userId,
        tier: from_candid_CourseTier_n49(_uploadFile, _downloadFile, value.tier),
        purchasedAt: value.purchasedAt,
        courseId: value.courseId
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _ApprovalStatus;
    principal: Principal;
}): {
    status: ApprovalStatus;
    principal: Principal;
} {
    return {
        status: from_candid_ApprovalStatus_n53(_uploadFile, _downloadFile, value.status),
        principal: value.principal
    };
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    premium: null;
} | {
    free: null;
} | {
    paid: null;
}): UserTier {
    return "premium" in value ? UserTier.premium : "free" in value ? UserTier.free : "paid" in value ? UserTier.paid : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: from_candid_record_n23(_uploadFile, _downloadFile, value.completed)
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    video: null;
} | {
    tool: null;
} | {
    article: null;
}): Variant_video_tool_article {
    return "video" in value ? Variant_video_tool_article.video : "tool" in value ? Variant_video_tool_article.tool : "article" in value ? Variant_video_tool_article.article : value;
}
function from_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    intermediate: null;
} | {
    beginner: null;
} | {
    advanced: null;
} | {
    professional: null;
}): CourseLevel {
    return "intermediate" in value ? CourseLevel.intermediate : "beginner" in value ? CourseLevel.beginner : "advanced" in value ? CourseLevel.advanced : "professional" in value ? CourseLevel.professional : value;
}
function from_candid_variant_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
} | {
    failed: null;
}): PaymentStatus {
    return "pending" in value ? PaymentStatus.pending : "completed" in value ? PaymentStatus.completed : "failed" in value ? PaymentStatus.failed : value;
}
function from_candid_variant_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): ApprovalStatus {
    return "pending" in value ? ApprovalStatus.pending : "approved" in value ? ApprovalStatus.approved : "rejected" in value ? ApprovalStatus.rejected : value;
}
function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CourseDescription>): Array<CourseDescription> {
    return value.map((x)=>from_candid_CourseDescription_n27(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CourseModule>): Array<CourseModule> {
    return value.map((x)=>from_candid_CourseModule_n32(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Resource>): Array<Resource> {
    return value.map((x)=>from_candid_Resource_n35(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CoursePurchase>): Array<CoursePurchase> {
    return value.map((x)=>from_candid_CoursePurchase_n45(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserApprovalInfo>): Array<UserApprovalInfo> {
    return value.map((x)=>from_candid_UserApprovalInfo_n51(_uploadFile, _downloadFile, x));
}
function to_candid_ApprovalStatus_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): _ApprovalStatus {
    return to_candid_variant_n59(_uploadFile, _downloadFile, value);
}
function to_candid_CourseTier_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CourseTier): _CourseTier {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_CreateCourseForm_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateCourseForm): _CreateCourseForm {
    return to_candid_record_n11(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentStatus_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentStatus): _PaymentStatus {
    return to_candid_variant_n61(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n56(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_UserTier_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserTier): _UserTier {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    tier: CourseTier;
    description: string;
    modules: Array<string>;
}): {
    title: string;
    tier: _CourseTier;
    description: string;
    modules: Array<string>;
} {
    return {
        title: value.title,
        tier: to_candid_CourseTier_n12(_uploadFile, _downloadFile, value.tier),
        description: value.description,
        modules: value.modules
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userTier: UserTier;
    interests: Array<string>;
    name: string;
    learningPath: Array<Id>;
}): {
    userTier: _UserTier;
    interests: Array<string>;
    name: string;
    learningPath: Array<_Id>;
} {
    return {
        userTier: to_candid_UserTier_n57(_uploadFile, _downloadFile, value.userTier),
        interests: value.interests,
        name: value.name,
        learningPath: value.learningPath
    };
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserTier): {
    premium: null;
} | {
    free: null;
} | {
    paid: null;
} {
    return value == UserTier.premium ? {
        premium: null
    } : value == UserTier.free ? {
        free: null
    } : value == UserTier.paid ? {
        paid: null
    } : value;
}
function to_candid_variant_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == ApprovalStatus.pending ? {
        pending: null
    } : value == ApprovalStatus.approved ? {
        approved: null
    } : value == ApprovalStatus.rejected ? {
        rejected: null
    } : value;
}
function to_candid_variant_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentStatus): {
    pending: null;
} | {
    completed: null;
} | {
    failed: null;
} {
    return value == PaymentStatus.pending ? {
        pending: null
    } : value == PaymentStatus.completed ? {
        completed: null
    } : value == PaymentStatus.failed ? {
        failed: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
